language: c
dist: trusty

arch:
  - amd64
  - ppc64le

install:
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.3.tar.gz
  - tar -xzvf cmake-3.4.3.tar.gz
  - cd cmake-3.4.3
  - ./bootstrap && make && sudo make install
script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
sudo: true
addons:
  apt:
    packages:
      - python-yaml
      - libtinfo-dev
compiler:
  - gcc
    #- clang

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fccf07549cf55d00de5d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
