language: c
dist: trusty

arch:
  - amd64
  - ppc64le

install:
  - wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
  - tar -xzf cmake-3.0.2-Linux-64.tar.gz
  - sudo cp -fR cmake-3.0.2-Linux-64/* /usr
  - rm -rf cmake-3.0.2-Linux-64
  - rm cmake-3.0.2-Linux-64.tar.gz
script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
sudo: true
addons:
  apt:
    packages:
      - python-yaml
      - libtinfo-dev
compiler:
  - gcc
    #- clang

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fccf07549cf55d00de5d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
